-- 0004 — regenerate the published suppressions document on every change.
-- docs/backend-supabase.md §6.1, schema.md §A.8, AD-5, FR-ERR-09, NFR-SEC-02.
--
-- DEVIATION FROM b1 §3, STATED RATHER THAN HIDDEN.
-- b1 asks for "a trigger regenerating suppressions.json into Storage on every change". Postgres
-- cannot write object bytes into Supabase Storage: Storage keeps bytes in its own backend (S3 or a
-- file volume) behind an HTTP API, and `storage.objects` is only its metadata table. The two ways
-- to make a trigger reach that API are `pg_net` (or plpython/http) carrying a service key inside
-- the database, and design §8 says the service_role key belongs in Edge Function environment and
-- CI secrets, "nowhere else".
--
-- So the trigger does the part that must be transactional — deriving the document, atomically,
-- from the same statement that changed a suppression — and publication is a read of one row by a
-- privileged caller (an Edge Function or a scheduled job). Nothing about the CLIENT's contract
-- changes: it still fetches one static, schema-validated JSON file over TLS, still discards
-- anything malformed in favour of the last good copy, still never blocks launch.

create table ops.suppressions_document (
  -- Exactly one row, forever. The check is what makes that structural rather than a convention.
  id           boolean primary key default true check (id),
  document     jsonb  not null,
  generated_at timestamptz not null default now()
);

alter table ops.suppressions_document enable row level security;
alter table ops.suppressions_document force  row level security;

comment on table ops.suppressions_document is
  'The rendered schema-2 suppressions.json (schema.md §A.8). Regenerated by trigger on every change to ops.suppressions; published to Storage by a service-role caller, never by the database itself.';

-- Not `security definer`: it is called only from triggers on ops.suppressions, which only a
-- service-role caller can write, and definer rights would buy nothing while widening the blast
-- radius (§8.1 case 3). `set search_path = ''` regardless, with every name qualified.
create or replace function ops.rebuild_suppressions_document() returns trigger
language plpgsql
set search_path = ''
as $$
declare
  doc jsonb;
begin
  select jsonb_build_object(
           -- schema 2. s3 §7 added the third array. A schema-1 document must keep validating on
           -- the client and simply carry no sidequests (`decodeIfPresent … ?? []`), because a
           -- validation failure sends the app to its last good copy and the failure mode is a
           -- withdrawal that silently stops applying — the exact thing AD-5 exists to prevent.
           'schemaVersion', 2,
           'updatedAt', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           'suppressedPlaceIds',
             coalesce(jsonb_agg(s.entity_id order by s.entity_id)
                      filter (where s.entity_type = 'place'), '[]'::jsonb),
           'suppressedQuestIds',
             coalesce(jsonb_agg(s.entity_id order by s.entity_id)
                      filter (where s.entity_type = 'quest'), '[]'::jsonb),
           'suppressedSideQuestIds',
             coalesce(jsonb_agg(s.entity_id order by s.entity_id)
                      filter (where s.entity_type = 'sidequest'), '[]'::jsonb)
         )
    into doc
    from ops.suppressions s
   where s.released_at is null;

  insert into ops.suppressions_document as d (id, document, generated_at)
  values (true, doc, now())
  on conflict (id) do update set document = excluded.document, generated_at = excluded.generated_at;

  return null;   -- AFTER … FOR EACH STATEMENT
end $$;

create trigger suppressions_publish
  after insert or update or delete on ops.suppressions
  for each statement execute function ops.rebuild_suppressions_document();

-- Seed the document so a client fetching before the first suppression gets a valid schema-2 file
-- rather than nothing.
insert into ops.suppressions_document (id, document)
values (true, jsonb_build_object(
  'schemaVersion', 2,
  'updatedAt', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
  'suppressedPlaceIds', '[]'::jsonb,
  'suppressedQuestIds', '[]'::jsonb,
  'suppressedSideQuestIds', '[]'::jsonb
))
on conflict (id) do nothing;
